# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/plugable-projects-audit.js
#####

SDLC_PLUGABLE_PROJECTS_AUDIT_JS:=$(DIST)/plugable-projects-audit.js
SDLC_PLUGABLE_PROJECTS_AUDIT_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(SDLC_PLUGABLE_PROJECTS_AUDIT_JS)

$(SDLC_PLUGABLE_PROJECTS_AUDIT_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_PLUGABLE_PROJECTS_AUDIT_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/plugable-projects-audit.js
#####
